version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

phases:
  pre_build:
    commands:
      - mkdir /tmp/src/
      - mv $CODEBUILD_SRC_DIR/* /tmp/src/
      - cd /tmp/src/
      - python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip==20.1.1 && pip install -r rest_api/requirements.txt && python -m pytest tests/ -v && deactivate && rm -rf venv
  build:
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - /tmp/src/packaged.yaml
    - /tmp/src/template.yaml
  discard-paths: yes
