AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'flask-email-api-serverless

  Example project for sending an email via SendGrid and using templates stored in
  S3

  '
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: '''GET,HEAD,OPTIONS,PUT'''
      AllowHeaders: '''Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'''
      AllowOrigin: '''*'''
Parameters:
  CorsOrigins:
    Type: String
  SendGridKey:
    Type: String
  FromEmail:
    Type: String
  DBUrl:
    Type: String
  ExecEnv:
    Type: String
    AllowedValues:
    - local
    - dev
    - stage
    - prod
    Default: prod
Resources:
  SendEmailSendGridDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-tujg7utm2u1n/dd9bf74288e110edfdf86e4cebec1110
      Handler: app.app
      Runtime: python3.8
      AutoPublishAlias: live
      Environment:
        Variables:
          DB_URL:
            Ref: DBUrl
          ALLOWED_ORIGINS:
            Ref: CorsOrigins
          SENDGRID_KEY:
            Ref: SendGridKey
          FROM_EMAIL:
            Ref: FromEmail
          EXEC_ENV:
            Ref: ExecEnv
      Events:
        SendEmailSendGridDemoAPI:
          Type: Api
          Properties:
            Path: /send-number-email/
            Method: post
        PingPongHealthCheck:
          Type: Api
          Properties:
            Path: /ping/
            Method: get
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Hooks:
          PreTraffic:
            Ref: beforeAllowTraffic
          PostTraffic:
            Ref: afterAllowTraffic
  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: SendEmailSendGridDemoFunction.Version
      Runtime: nodejs10.x
      FunctionName: CodeDeployHook_beforeAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: SendEmailSendGridDemoFunction.Version
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-tujg7utm2u1n/dc6bccf9488d37be1f4fb3a135a99a11
  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: SendEmailSendGridDemoFunction.Version
      Runtime: nodejs10.x
      FunctionName: CodeDeployHook_afterAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: SendEmailSendGridDemoFunction.Version
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-tujg7utm2u1n/dc6bccf9488d37be1f4fb3a135a99a11
Outputs:
  SendEmailSendGridDemoApi:
    Description: API Gateway endpoint URL for Prod stage for Send Email SendGrid Demo
      function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-number-email/
  PingPongHealthCheck:
    Description: API Gateway endpoint URL for Prod stage for health check
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping/
  SendEmailSendGridDemoFunction:
    Description: Send Email SendGrid Demo Function ARN
    Value:
      Fn::GetAtt:
      - SendEmailSendGridDemoFunction
      - Arn
  SendEmailSendGridDemoFunctionIamRole:
    Description: Implicit IAM Role created for Send Email SendGrid Demo function
    Value:
      Fn::GetAtt:
      - SendEmailSendGridDemoFunctionRole
      - Arn
