version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "numberemailer-sender"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zez2v5ke4nzp"
s3_prefix = "numberemailer-sender"
region = "us-east-2"
profile = "ambassador"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
